### ISSUE TITLE
Bug on hidden elements

### ISSUE THREAD

**Issue by alvarotrigo** [jmosbech/StickyTableHeaders#103]
[Reproduction of the problem](http://jsfiddle.net/ennadpx6/)

It is very common to have hidden elements on page load nowadays.

**Comment by jmosbech** [comment]
The problem is that you're styling the `table` element directly and the StickyTableHeaders creates a hidden table clone behind the scenes. Fixing this would mean rewriting the entire plugin. Instead I suggest you avoid targeting the table element directly in your css.

**Comment by alvarotrigo** [comment]
Are you just talking about the use of a generic selector such as `table` to define the `display:none`?
If so, [here you have the same problem](http://jsfiddle.net/ennadpx6/1/) when using a specific ID to set the visibility of the table.

**Comment by jmosbech** [comment]
The problem is this fellow: 

    $('table').show();

You're basically telling jquery to show _all_ tables on the entire page - including the hidden one the plugin is using behind the scenes. If you limit this selector you should be fine.

**Comment by alvarotrigo** [comment]
> The problem is this fellow:

I changed it [in the last link I provided](http://jsfiddle.net/ennadpx6/2/) and the plugin still not responding properly:

```javascript
setTimeout(function(){
    $('#myTable').show();
}, 1000);
```

**Comment by alvarotrigo** [comment]
It only seems to work as expected after scrolling up and down on the broken table.

**Comment by alvarotrigo** [comment]
Personally I would say the problem is actually a bug as the plugin is unable to retrieve the `width` of a `display:none` element. That's why it is currently setting the with to 0 for all the headers:

```css
<tr>
            <th style="min-width: 0px; max-width: 0px;">Type</th>
            <th style="min-width: 0px; max-width: 0px;">Ocurred</th>
            <th style="min-width: 0px; max-width: 0px;">Status</th>
            <th style="min-width: 0px; max-width: 0px;">Owner</th>
            <th style="min-width: 0px; max-width: 0px;">Notified</th>
            <th style="min-width: 0px; max-width: 0px;">Specified</th>
            <th style="min-width: 0px; max-width: 0px;">Message</th>
        </tr>```

**Comment by jmosbech** [comment]
That could be. Why do you initialize the plugin before the table is visible anyway? Did you try to do it after calling `show()`?

**Comment by alvarotrigo** [comment]
@jmosbech just trying to apply it in a generic way, as in the application I'm making there might be multiple tables using fixed headers and being fired from different events / functions.
