### ISSUE TITLE
Incompatibility with react

### ISSUE THREAD

**Issue by sobrinho** [jmosbech/StickyTableHeaders#108]
There is a incompatibility with react because this plugin clones the table header which may have the `data-react-id` and then there will be two elements using the same id, which breaks react.

What we can do?

1. Do not clone `data-react-id` properties from the clone (too specific but would work)
2. Remove the original table header from the DOM when the clone is present (how to deal with mutations on the clone after restoring the original one?)
3. Provides a hook or event to be called at a some point which we can manipulate the cloned header (that would allow to do the 1st option but not on the plugin)

What you think?

**Comment by sobrinho** [comment]
My current workaround:

``` javascript
  componentDidMount () {
    $(this.refs.table).stickyTableHeaders();

    // Since stickyTableHeaders clones the header, we need to remove the
    // data-reactid from the clone because react doesn't allow two elements
    // using the same id.
    //
    // See https://github.com/jmosbech/StickyTableHeaders/issues/108
    $(".tableFloatingHeader", this.refs.table)
      .find("[data-reactid]")
      .andSelf()
      .attr("data-reactid", null);
  }
```

**Comment by jmosbech** [comment]
This is a bit tricky because React expects full control of the DOM if it has to handle the rendering. Have you looked at [findDOMNode](http://facebook.github.io/react/docs/working-with-the-browser.html#refs-and-finddomnode)?

**Comment by sobrinho** [comment]
Yes but isn't related to the issue, `findDOMNode` and `this.refs.X` both returns a DOM node.

There is a workaround as I wrote above but isn't elegant, although I think there is nothing we can do right now.

I read somewhere that they are going to remove the `data-reactid` from the DOM at some point, so, I'm closing.
