### ISSUE TITLE
Sticky for dynamic tables

### ISSUE THREAD

**Issue by cbloss** [jmosbech/StickyTableHeaders#118]
Hey!

I was having an issue with StickyTableHeaders with tables that are dynamic. I have this one table that was adding columns via an AJAX call. Here was my solution: "destroy" the sticky header, remove all the styles to the th tags and then re-enable the sticky headers. 

Is this something that may be adapted to the destroy call?

**Comment by hanoncs** [comment]
I had the same issue. I may look at completing and submitting pull request if I can find the time.

**Comment by stosh15x** [comment]
You could always call the following in your $.ajax

```
complete: function(){
  $('table').stickyTableHeaders('destroy');
  $('table').stickyTableHeaders();
}
```

**Comment by cbloss** [comment]
Hey @stosh15x !

That was kind of what I ended up doing. I can't remember the final code (it was awhile ago), but destroying it and just re-enabling worked. :)
