### ISSUE TITLE
How to use with Angular2 ?

### ISSUE THREAD

**Issue by arunvelsriram** [jmosbech/StickyTableHeaders#131]
Hi. This is not an issue but a request to add examples of using StickyTableHeaders with Angular2.

Thanks.

**Comment by arunvelsriram** [comment]
I was able to use it with Angular 2 via directive.

Here is the directive:
```
// sticky-table-header.directive.ts

import { Directive, ElementRef } from '@angular/core';

@Directive({
  selector: '[stickyTableHeader]'
})
export class StickyTableHeaderDirective {

  constructor(private el: ElementRef) {}

  ngAfterViewInit() {
    $(this.el.nativeElement).stickyTableHeaders();
  }

}
```

I use Angular CLI to manage my app. So I had to add the following to `angular-cli.json`:

```
"scripts": [
  "../node_modules/jquery/dist/jquery.js",
  "../node_modules/sticky-table-headers/js/jquery.stickytableheaders.js"
],
```

**Comment by ghost** [comment]
Hi how do i use follwing with angular 5:
$('table').stickyTableHeaders({scrollableArea: $('.scrollable-area')});

**Comment by paulbonner** [comment]
@arunvelsriram -- This is terrific, thanks!

@sushmit-oodles -- Pass the classname or the entire hash into the directive using an @Input property. see https://angular.io/guide/attribute-directives
