### ISSUE TITLE
This example of mine wont work

### ISSUE THREAD

**Issue by kieronboz** [jmosbech/StickyTableHeaders#75]
https://gist.github.com/kieronboz/ed6dec78b3be2ba51e7d

Sorry to gist it, but ive imported script, applied to the tables, also tried a different id when running the script, no joy. any help appreciated.

**Comment by dtwen** [comment]
Make sure you have the proper table syntax and tags.  It needs this to work. 
`<Table><thead></thead><tbody>...</tbody></table>`

**Comment by jmosbech** [comment]
Considering this fixed. Thanks for chipping in @dtwen
