### ISSUE TITLE
Demo JFiddle Library Differs from Master

### ISSUE THREAD

**Issue by qwwqwwq** [jmosbech/StickyTableHeaders#78]
Copying JS from demo worked perfectly for my simple use case, while using the JS from master failed horribly (table header appeared position in the middle of the page)

**Comment by jmosbech** [comment]
Yeah - the fiddle might be an older version. Could you provide additional details about the error you're seeing? (Preferably including code)

**Comment by jmosbech** [comment]
I updated the fiddle to the latest version (0.1.15). Please re-open if you're still experiencing issues.
