### ISSUE TITLE
had issue with "TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by mckinleymedia** [jmosbech/StickyTableHeaders#81]
To solve this "undefined" issue, I moved jquery and the stickyTableHeaders script to the top of my script list.  However, I expect this will fail sometimes.

Can you tell me how I can specify that the script needs to be loaded before the directive is processed?

**Comment by jmosbech** [comment]
Uhm. Sorry - I probably need a few more details to say something about this. The script requires jquery to be loaded. It doesn't have other dependencies.

**Comment by mckinleymedia** [comment]
Hi.  I've got it working for now by moving it up to the top of the list, but it was always after jQuery.  To fix it, I had to put both it and jQuery before angular.  When I've got time, I'll come back to it....
