### ISSUE TITLE
Additional features?

### ISSUE THREAD

**Issue by mckinleymedia** [jmosbech/StickyTableHeaders#82]
Hey.  This script works really well for me so far.  However, I want to add a bunch of features to it:
1 - Enable an additional non-table fixed header (I've got a toolbar I want to fix on the page as well).  I've started in this - I figure I'll create a new variable "type" that'll say whether it's a table or something else.
2 - Freeze selected regular rows inside the same table.
3 - Freeze a selected number of columns.
4 - Ability to toggle frozen parts.

Has anyone done anything of these things with this script?

**Comment by jmosbech** [comment]
1) if I understand you correctly this scenario is covered by one of the demos
2) Not possible out of the box.
3) Not possible out of the box, but maybe you can modify the contents of the cloned header and see where it gets you.
4) You can toggle the entire plugin (check the demos) but I'm not sure that's what you want?

**Comment by mckinleymedia** [comment]
Hi.
1 - Well, not really - I was looking for a header that is also dynamically engaged, not just set as "fixed."  But this capability should be pretty easy to modify so it works with your script.
2 - Yeah, I figured I'd need to modify the code for each of these things.
3 - The tricky part for me has been that cloning the existing table can get in the way of the Angular processes, though your script didn't have those issues.  I'll use what you've got as a guide....
4 - Nope.  I want to be able to toggle individual rows in addition to the header row - the idea is that the user can lock one or more rows to compare with other rows.  This means I might need a separate frozen header for each row.
No worries - I think I can make it work.
Cheers,
--Will
