### ISSUE TITLE
MIT license for clarity, vs. your custom license

### ISSUE THREAD

**Issue by NewAlexandria** [jmosbech/StickyTableHeaders#83]
The license you have up is not easy to work with, from a legal standpoint, because it does not fall under one of the standardized software license that have been evaluated by the legal industry, and where case history exists.  Because of that risk, you will get limited corporate adoption, thus collaboration.  

Since your license essentially reads like an MIT license, I encourage you to change it for the ends of more involvement from the corporate community. If you chose GPL or its variants, you will specifically limit corporate involvement due to copyleft.

Thanks!

**Comment by jmosbech** [comment]
The license is MIT. Sorry if that somehow is unclear. I will update the readme.
