### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by deadend5001** [jmosbech/StickyTableHeaders#90]
I am using stickyTableHeaders with a table header that has a checkbox in the table header. This checkbox when clicked selects all checkboxes in the table (aka select all checkbox).

What I am finding is that with stickyTableHeaders enabled on these tables...the checkbox is always submitted in it's default state. So if it was checked on load it is checked when the form is submitted.

I think this is because technically there are two checkboxes with the same value and one is getting updated and the other is not?

Thoughts?

**Comment by jmosbech** [comment]
Sorry for the long response time on this. I suppose you probably found a solution on this already, but in any case: You might be able to subscribe to clicks on the both versions of the checkboxes and in the click handler you update the invisible checkbox. In that way the two values are always the same.
