### ISSUE TITLE
How do we have the header have a different background once it's sticky?

### ISSUE THREAD

**Issue by rzfarrell** [jmosbech/StickyTableHeaders#92]
Hello, it seems that I can not have the sticky header have a different background than the original header.  I don't want the sticky header to have a background until the page scrolls enough to activate it.

This is what I am looking for:

Default:
![image](https://cloud.githubusercontent.com/assets/1565971/7140789/63bdbeca-e29b-11e4-99b6-ff254c0742f2.png)

Sticky:
![image](https://cloud.githubusercontent.com/assets/1565971/7140814/82bc9418-e29b-11e4-8f47-f7f3b43a794c.png)

Am I missing something?

**Comment by jmosbech** [comment]
The two modes have different class names `tableFloatingHeaderOriginal` and `tableFloatingHeader`. Did you try to use those to solve the issue?
