### ISSUE TITLE
Old header still visible as sticky header is put in place when header cells have inner tag content

### ISSUE THREAD

**Issue by Millzy** [jmosbech/StickyTableHeaders#95]
Issue:

I can see the original header as the clone header becomes visible, I think this is due to the header cells having more than just text in them. This is happening in IE10, not sure in other browsers.
![header showing old header](https://cloud.githubusercontent.com/assets/12246636/7467551/3a4090be-f33e-11e4-8f7e-a618ed417c6c.png)

I have overcome this by adding the opacity: 0.0 into your code, could probably clean it up better than I have though:
![header showing old header fix](https://cloud.githubusercontent.com/assets/12246636/7467571/af409670-f33e-11e4-9493-3d50dbc903ab.png)

**Comment by jmosbech** [comment]
@Millzy, thanks for submitting this (and sorry about the long response time). Would you by any means be able to provide a fiddle that demonstrates the issue?

**Comment by jmosbech** [comment]
Pushed a fix for this. Please let me know how it works.

**Comment by Millzy** [comment]
Thanks jmosbech, sorry I couldn't get a fiddle going, I use the plugin in a massive intranet reporting system and time is of the essence.  I have updated my project with the latest version and the issue looks to be resolved.  Good job, great plugin BTW!
